import type { Contribution } from "./";

export const ExampleContribution: Contribution = {
  amount: "",
  type: "string;",
  subType: "string;",
  inKindType: "string;",
  contributorType: "string;",
  oaeType: "string;",
  contrPrefix: "string;",
  firstName: "string;",
  middleInitial: "string;",
  lastName: "string;",
  suffix: "string;",
  title: "string;",
  name: "string;",
  address1: "string;",
  address2: "string;",
  city: "string;",
  state: "string;",
  zip: "string;",
  county: "string;",
  email: "string;",
  phone: "string;",
  phoneType: "string;",
  checkNumber: "string;",
  occupation: "string;",
  employerName: "string;",
  employerCity: "string;",
  employerState: "string;",
  employerCountry: "string;",
  notes: "string;",
  paymentMethod: "string;",
  date: "string;",
  occupationLetterDate: "string;",
};
